theme: jekyll-theme-cayman
title: Attitudes Toward Deprescribing among Older Adults with Dementia in the US
description: Exploring attitudes of community-dwelling older adults with dementia and their caregiversâ€™ attitude toward medications and their willingness to deprescribe
